### ISSUE TITLE
necessary files

### ISSUE THREAD

**Issue by mx-ecust** [MarioniLab/SpatialMouseAtlas2020#1]
The code in scrpit uses some necessary files, such as fovinfo.csv and smFISH__ gene_ key__ New.tab, can the author provide it?

**Comment by shazanfar** [comment]
Hi there, I have now added the "barcoding_info" and "fov_info" folders into this repository.

Note that the smFISH__ gene_ key__ New.tab file has been updated to Sequential_readout-ID_v3_TL_ID_SG.csv which contains more specific information on the probe and colours. Hope that helps!

Best wishes,
Shila
